### ISSUE TITLE
complete?

### ISSUE THREAD

**Issue by drummerclint** [Zayik/CommandSender#1]
Hey, 
Just wondering if this is fully fledged and working and how do I go about installing it.

Thanks!
Clint

**Comment by Zayik** [comment]
Hey Clint, 

I apologize for not getting back to you sooner. I had this in the back of my mind, and forgot about it when I finally had free time to sit down and look at this. 

The Command Sender is complete. Since it uses udp connection, it won't ensure the message is sent. Bright side is that it doesn't need to worry about keeping a connection with said server. 

I have included an Install file for this plugin in the Release folder. 
https://github.com/Zayik/CommandSender/tree/master/Release

I'll be including a test project so you can make sure the button presses on the streamdeck do in fact send a message. 

Thanks for your interest!
