### ISSUE TITLE
TCP Command not working

### ISSUE THREAD

**Issue by rwatkinsii** [Zayik/CommandSender#11]
If i send my command with packet sender, it works and if i send it from the original application it works. If i send it from your software from the stream deck it does not. I am attaching the Wireshark images that show it is somehow changing.
![Failed](https://user-images.githubusercontent.com/111670049/185773171-bcaba068-c2aa-4783-bdf2-17f577654b56.PNG)
![Successful](https://user-images.githubusercontent.com/111670049/185773172-8ea79e34-8ea0-48b9-89e6-23c947a91df0.PNG)

**Comment by Zayik** [comment]
Hey @rwatkinsii 
Thanks for your patience as I finally had a chance to look into this. 

It took me a while to figure out what the heck was going on, and luckily I've done just that! 

The behavior you are seeing isn't actually an issue with Command Sender, but more of type formatting issue. 
The stream deck plugin fields that you type stuff in is html-based.


When you try to input the string "<PST><AZIMUT H>85</AZIMUTH></ PST>\r", it is completely considering that a literal string. 

You'll notice the trouble maker area is the /r. This is a carriage return. However, in html, if you want to use these special characters, you need to use its escape sequence. 
![image](https://user-images.githubusercontent.com/8930730/186819392-786edf3d-afa1-4c9c-b217-70ff8a9d1c53.png)

So in command sender, you end up forming that string as the following: 
![image](https://user-images.githubusercontent.com/8930730/186820474-57f32cb8-1cec-42a9-add0-bd56e63003d1.png)

When using other programs such as Packet Sender or the original application, it is written as a typical string and isn't html-based, so that \r is being processed as a carriage return instead of two characters '/' and 'r'. 

Please let me know if that resolves your issue. 

Thanks for your interest!
