### ISSUE TITLE
New build doesn't work at all?

### ISSUE THREAD

**Issue by Jinx-IT** [Zayik/CommandSender#13]
I've installed the newest build and I get warning triangles when pushing the buttons on the stream deck.  If I revert to the other version I'm back where I started.

**Comment by Zayik** [comment]
Hey there. Not sure why that would give you issues since the change was
relatively small. Ill do some additional testing to see if I can find
anything wrong.

Per chance can you give me an example string that you are using for your
command pressed/command released. That would help in the debugging.

**Comment by Jinx-IT** [comment]
Still working with the same strings…per your msg…here’s the strings.

Packet Sender uses regular string:
CC 8023 1 780 \r

Command Sender uses literal string and then uses html decoding for special characters:
CC 8023 1 780 &#13;

A note for you though…the string you showed me in command sender (before upgrading to the latest release) doesn’t work either.  Let me clarify that the spaces between CC, 8023, 1, and 780 all matter.  The string calls for a controller change (CC) of parameter 8023 to increase (1 is increase, 0 is decrease) an amount of 780 (which equates to 1dB).  See page 8 of this doc: Composer-Control-Protocol-v7.0-080918.pdf (symetrix.co)<https://www.symetrix.co/wp-content/uploads/2018/08/Composer-Control-Protocol-v7.0-080918.pdf>

And to clarify again, once upgraded to the new release, the actual stream deck press fails with the warning triangle.

Sincerely,

Destry Jinks Sr.
***@***.******@***.***>
407.574.6978
[jinxITsignature1]

**Comment by Zayik** [comment]
Thanks for that detailed explanation. 

Given I am abandoning the concept of dealing with html encoding/decoding in favor of unifying the tool to match what others do such as Packet Sender, I am not going to worry about diving into that aspect. 

That being said, I have identified two issues and have fixed them. 

1. The package I had was unfortunately a development version which has debugging requirements in order to work. This is what caused the yellow square to appear on the stream deck. I have corrected this and successfully sent a message to a tcp server via internet using the latest package.

2. I resolved a bug in that if the connection was lost to the server (Server restarts), the very first message sent would fail. (This would result in the command pressed failing to send while the command release would succeed. 

I hope this fix fairs much better and thanks for your patience!

**Comment by Jinx-IT** [comment]
So I should upgrade again, and go back to my packet sender style of commands?


Sincerely,

Destry Jinks Sr.
***@***.******@***.***>
407.574.6978
[jinxITsignature1]

**Comment by Zayik** [comment]
Yes, please upgrade again and go back to the packet sender style of commands.

**Comment by Jinx-IT** [comment]
We have full control!  Even on a couple of double commands (muting two channels at once, with a release).  You’re awesome!

Example of double command:

Pressed: CS 8034 65535 \r\nCS 8042 65535 \r

Released: CS 8034 0 \r\nCS 8042 0 \r


Sincerely,

Destry Jinks Sr.
***@***.******@***.***>
407.574.6978
[jinxITsignature1]
